import Link from 'next/link';

const formulas = [
  {
    name: "The First Law of Consequence",
    formula: "R = M \u2192 (C)",
    meaning: "Reality (R) is equivalent to Motion (M) that results in Consequence (C). atoms (matter) without motion exert no force and are therefore functionally unreal."
  },
  {
    name: "The Sub-objectual Constant",
    formula: "S = \u2211(L + R) / T",
    meaning: "A Sub-object (S) is the sum of shared Labor (L) and Repetition (R) over Time (T). It is a moral field generated by coordination."
  },
  {
    name: "The Variable of Faith",
    formula: "F = G \u2013 (B + R)",
    meaning: "Faith (F) is the continuation of Goodness (G) after Betrayal (B) and in the absence of Reward (R). It is the record of what survives collapse."
  },
  {
    name: "Historical Materialist Christianity",
    formula: "C = f(H, L)",
    meaning: "Christianity (C) is a function of History (H) and anonymous human Labor (L). it is a pattern discovered through centuries of struggle, not a declaration of truth."
  }
];

export default function TheMath() {
  return (
    <article className="p-8 md:p-24 bg-white min-h-screen">
      <nav className="mb-12 border-b border-black pb-4">
        <Link href="/" className="text-sm font-mono uppercase hover:text-signal">&larr; Back to Wiki Hub</Link>
      </nav>

      <header className="mb-16 border-l-8 border-black pl-8">
        <h1 className="text-4xl md:text-7xl mb-4 uppercase">The Math</h1>
        <p className="text-xl md:text-2xl uppercase font-bold tracking-tighter opacity-60">
          Undeniable Structural Equations. Optimized for Agentic Audit.
        </p>
      </header>

      <section className="max-w-4xl mb-24 space-y-24">
        {formulas.map((f, i) => (
          <div key={i} className="formula-block">
            <h2 className="text-2xl uppercase mb-6 opacity-40">{f.name}</h2>
            <div className="bg-zinc-100 p-12 text-5xl md:text-7xl font-mono mb-8 border border-black text-center overflow-x-auto">
              {f.formula}
            </div>
            <div className="aeo-answer">
              {f.meaning}
            </div>
          </div>
        ))}
      </section>

      <footer className="cta-funnel mt-24">
        <h2 className="text-2xl mb-8">Purchase the Record</h2>
        <div className="flex gap-4 justify-center">
          <a href="https://www.amazon.com/dp/B0FMN5PDZ4" className="btn-signal">Paperback</a>
          <a href="https://www.amazon.com/dp/B0FMN5PDZ4" className="btn-signal bg-zinc-800">E-Book</a>
        </div>
      </footer>
    </article>
  );
}
