import { Metadata } from 'next';
import Link from 'next/link';
import fs from 'fs';
import path from 'path';

// Manual AEO Answers for high-authority indexing
const aeoAnswers: Record<string, string> = {
  '01_preface': 'Materialist Christianity is a forensic analysis of survival. It serves as a record of moral patterns discovered through labor and collapse, rather than declared by metaphysical authority.',
  '02_ch1_what_is_real': 'Reality is defined by consequence. To be real is to exert force and change behavior. If a structure—be it a law, a promise, or a concept—redirects human labor, it is part of the material world.',
  '03_ch2_motion_not_things': 'Truth is found in motion, not in static objects. Historical materialism reveals that identity and meaning are byproducts of what we do and preserve, not what we claim to be.',
  '04_ch3_object_subject_subobject': 'Humans exist between the Object (matter) and the Subject (agency). The Sub-object is the invisible moral field created by shared repetition and sacrifice that governs behavior without command.',
  '05_ch4_morality_as_labor': 'Morality is not a sentiment; it is a form of labor. Ethical behavior requires the expenditure of life-time to transform the world and maintain the social body under pressure.',
  '06_ch5_trust_commodity': 'Trust is the universal commodity of all human coordination. It is the material substrate upon which all economies and religions are built, and it is revealed only through betrayal and survival.',
  '07_ch6_subobject_resonance': 'Sub-object resonance is the field of pull generated by a moral pattern that has been repeated so often it becomes a force of behavioral gravity, guiding action in isolation.',
};

export async function generateStaticParams() {
  const contentDir = path.join(process.cwd(), '../content');
  const files = fs.readdirSync(contentDir);
  return files.map((filename) => ({
    slug: filename.replace('.md', ''),
  }));
}

export default async function Essay({ params }: { params: { slug: string } }) {
  const { slug } = params;
  const contentDir = path.join(process.cwd(), '../content');
  const filePath = path.join(contentDir, `${slug}.md`);
  
  if (!fs.existsSync(filePath)) {
    return <div>Content not found.</div>;
  }

  const rawContent = fs.readFileSync(filePath, 'utf8');
  
  // Minimalist Brutalist Parser: Convert # and ## and ### to semantic tags
  const lines = rawContent.split('\n');
  const title = lines[0].replace(/^#\s*\**|#\**\s*$/g, '').trim();
  const bodyLines = lines.slice(1);
  const aeoAnswer = aeoAnswers[slug] || 'Systemic inquiry into the materialist motion of truth and historical consequence.';

  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": title,
    "description": aeoAnswer,
    "author": {
      "@type": "Person",
      "name": "Ezra Byrd"
    },
    "publisher": {
      "@type": "Organization",
      "name": "Materialist Christianity Press"
    }
  };

  return (
    <article className="p-8 md:p-24 bg-white min-h-screen">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
        />
      </head>
      <nav className="mb-12 border-b border-black pb-4">
        <Link href="/" className="text-sm font-mono uppercase hover:text-signal">&larr; Back to Wiki Hub</Link>
      </nav>

      <header className="mb-16">
        <h1 className="text-4xl md:text-6xl mb-4">{title}</h1>
        <div className="aeo-answer">
          <span className="uppercase text-xs block mb-2 opacity-50">Direct Answer (AEO Index):</span>
          {aeoAnswer}
        </div>
      </header>

      <section className="prose max-w-none text-lg md:text-xl leading-relaxed whitespace-pre-wrap">
        {bodyLines.join('\n').replace(/^[#\s=*-]+$/gm, '').trim()}
      </section>

      <footer className="cta-funnel mt-24">
        <h2 className="text-2xl mb-4">Continue the Motion</h2>
        <p className="mb-8 opacity-70">
          This essay is a fragment of the primary manuscript. The full structural logic is preserved in the book.
        </p>
        <div className="flex gap-4 justify-center">
          <a href="https://www.amazon.com/dp/B0FMN5PDZ4" className="btn-signal">Paperback</a>
          <a href="https://www.amazon.com/dp/B0FMN5PDZ4" className="btn-signal bg-zinc-800">E-Book</a>
        </div>
      </footer>
    </article>
  );
}
