import os
import json

def generate_manifest(raw_assets_dir, output_file):
    manifest = {
        "essays": [],
        "images": [],
        "documents": [],
        "other": []
    }

    essay_keywords = ["essay", "article", "manuscript", "subobject", "morality", "christianity"]
    image_exts = [".jpg", ".jpeg", ".png", ".webp", ".heic"]
    doc_exts = [".docx", ".pdf", ".md", ".txt"]

    for root, dirs, files in os.walk(raw_assets_dir):
        for file in files:
            path = os.path.relpath(os.path.join(root, file), raw_assets_dir)
            ext = os.path.splitext(file)[1].lower()
            
            # Skip noise
            if file in ["chat.html", "export_manifest.json", "user.json", "user_settings.json"]:
                continue
            if "conversations" in file and ext == ".json":
                continue

            entry = {
                "name": file,
                "path": path,
                "size_kb": round(os.path.getsize(os.path.join(root, file)) / 1024, 2)
            }

            if any(k in file.lower() for k in essay_keywords) and ext in doc_exts:
                manifest["essays"].append(entry)
            elif ext in image_exts:
                manifest["images"].append(entry)
            elif ext in doc_exts:
                manifest["documents"].append(entry)
            else:
                manifest["other"].append(entry)

    # Sort each category
    for key in manifest:
        manifest[key].sort(key=lambda x: x["name"])

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# Asset Manifest: Materialist Christianity\n\n")
        f.write("Generated by William for high-torque retrieval.\n\n")
        
        f.write("## 📝 Found Essays & Philosophical Texts\n")
        if manifest["essays"]:
            for e in manifest["essays"]:
                f.write(f"- [{e['name']}]({e['path']}) ({e['size_kb']} KB)\n")
        else:
            f.write("No specific essays identified by keywords.\n")

        f.write("\n## 🖼️ Media Assets (Images & Graphics)\n")
        # Visual assets are heavy. We only list a sample or summary if too many.
        if len(manifest["images"]) > 50:
            f.write(f"Total Images: {len(manifest['images'])}\n")
            f.write("Top 20 Visuals:\n")
            for img in manifest["images"][:20]:
                f.write(f"- [{img['name']}]({img['path']}) ({img['size_kb']} KB)\n")
        else:
            for img in manifest["images"]:
                f.write(f"- [{img['name']}]({img['path']}) ({img['size_kb']} KB)\n")

        f.write("\n## 📚 General Documents\n")
        for d in manifest["documents"]:
            # Avoid repeating essays
            if d not in manifest["essays"]:
                f.write(f"- [{d['name']}]({d['path']}) ({d['size_kb']} KB)\n")

    print(f"Manifest written to {output_file}")

if __name__ == "__main__":
    raw_dir = r"c:\Users\ezrab\OneDrive - Durham Technical Community College\Desktop\MCS\materialistchristianity-site\raw_assets"
    output = r"c:\Users\ezrab\OneDrive - Durham Technical Community College\Desktop\MCS\materialistchristianity-site\ASSET_MANIFEST.md"
    generate_manifest(raw_dir, output)
