const fs = require('fs');
const path = require('path');

const mapIn = path.join(process.cwd(), 'william-engine/lab/content_map.json');
const mapOut = path.join(process.cwd(), 'src/lib/content_map.ts');

if (!fs.existsSync(mapIn)) {
  console.error('❌ Missing source map: ' + mapIn);
  process.exit(1);
}

const mapData = JSON.parse(fs.readFileSync(mapIn, 'utf8'));
const content = `/**
 * @generated by William Engine - Categorical Path Restoration
 * 100% accurate slug-to-directory mapping.
 */
export const CONTENT_MAP: Record<string, string> = ${JSON.stringify(mapData, null, 2)};
`;

fs.writeFileSync(mapOut, content);
console.log('✅ src/lib/content_map.ts generated successfully.');
